line-length = 100
# Assume Python 3.13
target-version = "py313"

[lint]
select = ["ALL"]
ignore = ["N813", "PLW2901", "DTZ005", "TD002", "TD003", "FIX002"]

[lint.per-file-ignores]
"tests/*.py" = ["S101", "D103", "PLR2004", "SLF001"]

[lint.pylint]
max-args = 15

[format]
docstring-code-format = true
